[build]
  publish = "src"
  functions = "netlify/functions"

[[redirects]]
  from = "/dd-wheel/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/dd-wheel/*"
  to = "/dd-wheel/:splat"
  status = 200